apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: {{ .Values.flask.port }}
    targetPort: {{ .Values.flask.port }}
  type: ClusterIP