apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: {{ .Values.keycloak.port }}
    targetPort: {{ .Values.keycloak.port }}
  type: ClusterIP