apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mlflow
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: {{ .Values.mlflow.port }}
    targetPort: {{ .Values.mlflow.port }}
  type: ClusterIP